export const SET_DRIVER_LIST = 'SET_DRIVER_LIST';
export const SET_USERS_LIST = 'SET_USERS_LIST';
export const SET_HEALTH_DATA = 'SET_HEALTH_DATA';
export const SET_HEALTH_CATEGORY_DATA = 'SET_HEALTH_CATEGORY_DATA';